language: node_js
node_js:
  - "8"
addons:
  chrome: stable
notifications:
  email:
    recipients:
      - mengbinhao2018@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"